:doctype: article
:experimental: true


= 1. Customizing The Visual Asthetics of VS Code
Author: burkeholland@gmail.com

== Install a new editor theme

There are a bunch of themes to choose from. These are some of the more popular light and dark variants. The 3 in the last column are just for fun and making people laugh in presentations.

////
Yes, I know that Markdown has tables, but the syntax is....hard on the eyballs and it's really bad when you have lenghty content like links. IMO tables should probably not be in the spec. Too much "|" and "-" and ":---:".
////

.Table Themes
|===
| Light Themes | Dark Themes | Fun

| https://marketplace.visualstudio.com/items?itemName=bubersson.theme-hop-light[Hop Light]
| Night Owl 
| Slack

| Night Owl Light
| Cobalt2
| Hot Dog Stand

| Min
| Noctis
| win95

| Noctis
| Dracula
|

|===

== 2. Install a new icon theme

https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme[Material Icons]

https://marketplace.visualstudio.com/items?itemName=artlaman.chalice-icon-theme[Chalice Icons]

**Bonus**: Change the color of folders in the Material Icon theme pack and remove toggle arrows.

== 3. Switch to a nice programming font

. Install a new font.

=== Free Fonts

- https://github.com/tonsky/FiraCode[FiraCode]
- https://github.com/i-tu/Hasklig[Hasklig]
- https://larsenwork.com/monoid/[Monoid]

=== Paid Fonts

- https://dank.sh/[Dank Mono]
- https://www.typography.com/fonts/operator/styles[Operator Mono]
- https://www.fsd.it/shop/fonts/pragmatapro/[Pragmata Pro]


Enable the Font in User Settings kbd:[Cmd / Ctrl +,]

----
"editor.fontFamily": "Fira Code"
----

Enable font ligatures (if supported by your font)

----
"editor.fontLigatures": true
----

## 4. Turn off the Minimap

Open settings and turn off the Minimap. You don't use it. Free up some real estate.

```
"editor.minimap.enabled": false
```

---

## 5. Move Sidebar Right

Toggling the sidebar kbd:[Ctr/Cmd + B] is something that you will do a lot. It's disruptive to your brain to have it on the left because it pushes the context away and your eyes have to follow. Try it out for yourself. Expand and collapse the sidebar and watch how the editor portion gets shoved right.

Put the sidebar on the right by selecting "Toggle Sidebar Position" from the Command Palette. Notice the difference when you expand and collapse it.

---

## 6. Hide Open Editors

By defuault VS Code includes an "Open Editors" group in top of the explorer view. You can hide this to decrease the clutter in the Explorer Bar.

Open the user settings kbd:[`Ctrl/Cmd + ,`]

Set "Open Editors" to 0.

```
"explorer.openEditors.visible": 0
```

---

## 7. Change Default Settings View

By default, the Settings view us a UI. The JSON settings are easier to see all at once and the autocomplete is good enough that the UI is not necessary.

Open User Settings (`Ctrl/Cmd + ,`)...

```
workbench.settings.editor: "json"
```

You can always get back to the UI by opening the Command Palette (`Ctrl/Cmd + Shift + P`) and select "Open Settings UI".

**Bonus**: Map the command for "Open Settings UI" to a keyboard shortcut. Suggested - `Ctrl/Cmd + Option + ,`.

## 8. Easily identify editor instances with Peacock

1. Download the https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock&WT.mc_id=vscode-frontendmasters-buhollan[Peacock extension].

2. Open the Command Palette kbd:[Ctrl/Cmd + Shift + P] and select "Peacock: Enter A Color". Enter your favorite color hex value.

3. Switch to User Settings kbd:[Ctr/Cmd + ,]
